### ISSUE TITLE
Closures

### ISSUE THREAD

**Issue by mauro3** [JuliaIO/JLD2.jl#13]
Will/can JLD2 store closures?

**Comment by simonster** [comment]
Depends what you mean by "store." At the moment, JLD2 serializes functions like types, so it doesn't store the source of anonymous functions (actually the original source is entirely unavailable; all you can get is the lowered code), but it will store the closed-over values.

**Comment by mauro3** [comment]
That sounds good enough.  I'll give it a try.  Thanks!

**Comment by marius311** [comment]
Is there any hope of being able to reconstruct closures? JLD2 indeed stores the closured over variables as pointed out by @simonster, but you don't get back a callable function, instead you get back a JLD2.ReconstructedTypes (have checked with Julia 1.1.0 and JLD2 0.1.2). The expected behavior exists in BSON.jl so it must be in theory possible, e.g.:

```julia
using BSON
a = 2
f = x->a*x^2
BSON.@save "test.bson" f
# in new session:
using BSON
BSON.@load "test.bson" f
f(3) # gives 18
```
