### ISSUE TITLE
Migration plan?

### ISSUE THREAD

**Issue by simonster** [JuliaIO/JLD2.jl#14]
Since this package is now working on all platforms, I think it's about time to release it. I'm not sure exactly how to do that. I see a few options:

- Start with a separate package from JLD.jl, and merge once it's seen wider use. (The only potentially complication here is if/how the package should be integrated with FileIO.)
- Move code here to JLD.jl, but don't enable by default, since it hasn't received the same degree of testing. Once it sees wider use, enable it by default.
- Move code here to JLD.jl and immediately enable by default. I'm a little hesitant to do this, since there may be cases I'm not handling properly yet.

**Comment by simonster** [comment]
cc @timholy

**Comment by timholy** [comment]
I'm supportive! What about the following strategy?

- Tag a release of this under its current name (or JLDnative?)
- Push a branch, `jld_experimental`, to FileIO that points to this package rather than JLD.jl
- Make an announcement on discourse, encouraging brave testers to switch to the `jld_experimental` branch of FileIO
- Deal with any problems
- Once the dust settles, merge the `jld_experimental` branch into FileIO's master

That way, anyone who has problems can manually choose JLD even after we make the switch. I don't really see a lot of profit in changing the names/functionality of the repos, though of course we could contemplate that.

**Comment by simonster** [comment]
I opened a [PR against FileIO] (https://github.com/JuliaIO/FileIO.jl/pull/139) to tighten the magic for JLD and register JLD2 with the extension `.jld2`. This way, it should be possible for both packages to co-exist for now, and we can always reclaim `.jld` later if we want.

**Comment by ExpandingMan** [comment]
Are there any plans to move the name of this package to JLD.jl and deprecate the existing JLD.jl?  It does seem that development on that one has ceased and that this one is becoming much more widely used.

I ask because the 0.7 transition might be a good time to do this.

**Comment by JonasIsensee** [comment]
JLD and JLD2 have established their respective names. There is no point in renaming now.
