### ISSUE TITLE
Feature idea: convert `index` to string

### ISSUE THREAD

**Issue by glwagner** [JuliaIO/JLD2.jl#238]
A feature that might be user-friendly is to convert indices to strings with something like:

```julia
Base.getindex(file_or_group::Union{JLDFile, Group}, name) = getindex(file_or_group, string(name))
```

In my experience the primary conveniences of this behavior are the ability to use integers (and occasionally symbols) as keys.

For example, I often work with time-series data so that my files look something like

```
julia> file = jldopen("test.jld2", "a+")
JLDFile /Users/gregorywagner/Projects/LESbrary.jl/examples/test.jld2 (read/write)
  (no datasets)

julia> file["u/0"] = 1
1

julia> file["u/1"] = 2
2

julia> file
JLDFile /Users/gregorywagner/Projects/LESbrary.jl/examples/test.jld2 (read/write)
 └─📂 u
    ├─🔢 0
    └─🔢 1
```

I can access elements of the timeseries with

```julia
julia> u = file["u"]
JLD2.Group
 ├─🔢 0
 └─🔢 1

julia> u["0"]
1
```

but it would be really nice to be able to write `u[0]`, which currently returns

```
julia> u[0]
ERROR: MethodError: no method matching getindex(::JLD2.Group{JLD2.JLDFile{JLD2.MmapIO}}, ::Int64)
Closest candidates are:
  getindex(::JLD2.Group, ::AbstractString) at /Users/gregorywagner/.julia/packages/JLD2/4AJn8/src/groups.jl:92
Stacktrace:
 [1] top-level scope at REPL[14]:1
```

There could be pitfalls I can't anticipate. A more restricted feature would convert only "safe" types:

```julia
SafeIndexTypes = Union{Integer, Symbol}

Base.getindex(file_or_group::Union{JLDFile, Group}, name::SafeIndexTypes) = getindex(file_or_group, string(name))
```

If this is deemed too dangerous or surprising I am happy to close this issue. But I thought it couldn't hurt to ask.

**Comment by JonasIsensee** [comment]
Hi @glwagner !

this is an interesting idea.
First of all, since this is a one-line definition, there is nothing wrong with just defining this yourself in whatever library you would like to use it.

I wonder how useful this would be in general though. For example, it is not uncommon to convert integers to strings with some zero-padding. `string(5, pad=3) == "003"`
Another thing that is not clear is whether one should then allow the same thing for storing and what other types could hypothetically be allowed. It has to be made clear to users that the name in the file will always be a string and that you cannot expect full _reconstructability_ e.g. if you tried to store something with an integer as a name that you won't get back an integer when you load it.
In that sense my personal opinion would be to encourage people to add their own interface/ overloads as needed
but to keep the library free from implicit conversions.

I'm open for discussion. @lhupe  Do you have any opinion on this?

**Comment by lhupe** [comment]
Not really, but I tend to agree; I think a good API (especially for potentially heart attack inducing tasks like data IO) should be designed on a least-surprises basis, so something like this is questionable at best. 
After all, I'm still not quite at home with the fact that both HDF5-based IO packages interpret slashes in keys as path specifications. Things like this are nice when you know about them, but in general, users tend to not know things like this (until they first stumble upon them by chance).

**Comment by glwagner** [comment]
Okay, thanks for the discussion! Let's close for now. I agree that packages can provide such a custom implementation for specific uses in some form or another if they wish.
