### ISSUE TITLE
[FR] Support dictionaries with Symbol as key type

### ISSUE THREAD

**Issue by Datseris** [JuliaIO/JLD2.jl#268]
I'm not sure why dictionaries with Symbol as their key type are not allowed, but it would be useful if they were.

**Comment by JonasIsensee** [comment]
Hi George!

Please excuse the nitpicking: Dictionaries are in fact supported. Just not in the way you are thinking.

```
julia> using JLD2, FileIO

julia> d = Dict(:a => 1, :b => 3)
Dict{Symbol,Int64} with 2 entries:
  :a => 1
  :b => 3

julia> save("test.jld2", "mydict", d)

julia> load("test.jld2")
Dict{String,Any} with 1 entry:
  "mydict" => Dict(:a=>1,:b=>3)

julia> save("test.jld2", d)
Error encountered while saving "test.jld2".

Fatal error:
ERROR: ArgumentError: keys must be strings (the names of variables), got a
```

Internally `JLD2` works a lot like the folder structure on your computer and
where also all the folder and file names are strings. The fact that you
can "save" a dictionary with String keys is just a convenience function
that unrolls the keys and values into different entries in this 
structure. This happens at top-level but not recursively so in my example above it just stores dict as a single thing.
(You could ask: Why not always do it like that? If it is split into different entries then you can load just selected parts out of a large file and not have to load everything)

In principle it would be possible to do the same thing for a dictionary with `Symbol` keys and just convert them to `String` for saving but when you load the file it will
load data into a dict with `string` keys since it can't know that you wanted back symbols.

**Comment by JonasIsensee** [comment]
Of course you could always just define
```
tostringdict(d) = Dict(zip(String.(keys(d)), values(d)))
tosymboldict(d) = Dict(zip(Symbol.(keys(d)), values(d)))
```

**Comment by Datseris** [comment]
> The fact that you can "save" a dictionary with String keys is just a convenience function that unrolls the keys and values into different entries in this structure.

Sure, I know this. I don't care about doing it recursively (in fact, I would _actively advise against it_).

> In principle it would be possible to do the same thing for a dictionary with Symbol keys and just convert them to String for saving but when you load the file it will load data into a dict with string keys since it can't know that you wanted back symbols.

Yeah that's what I'm asking, although I can now see that there would be this inconsistency between write and read... So perhaps it is better not to do it in the end...?

Should we add these two functions in DrWatson?

**Comment by JonasIsensee** [comment]
> Yeah that's what I'm asking, although I can now see that there would be this inconsistency between write and read... So perhaps it is better not to do it in the end...?

Exactly, acting on the principle of least-surprise I'd like to avoid the inconsistency within JLD2.

> Should we add these two functions in DrWatson?

If you would use them, we can. The above might not be the most efficient though because I just made it up on the spot.
