### ISSUE TITLE
Note somewhere that reading from a .jld file is cached

### ISSUE THREAD

**Issue by thchr** [JuliaIO/JLD2.jl#277]
I had naively assumed that reading data would give a fresh instance of the saved data on every new read. This is apparently not so:
```jl
using JLD2
@save "test.jld2" v = [2,4,6]
global jldfile = jldopen("test.jld2", "r")
function f(perm)
    v = read(jldfile, "v") # or `jldfile["v"]`
    return permute!(v, perm)
end
f([1,2,3]) # [2,4,6]  <-- expected
f([3,2,1]) # [6,4,2]  <-- expected
f([1,2,3]) # [6,4,2]  <-- surprise: actually modified `jldfile["v"]`.
```
Contrary to my expectation, it seems that the loaded data `"v"` is cached after first read, and so if I modify it, any subsequent request to read `"v"` will not actually read it again, but just give me back the modified, cached data. Effectively, `jldfile` is closer to a genuine `Dict` than I had thought.

I think this is sufficiently surprising (e.g., if compared with, say, reading a JSON file or a text file) that it should be mentioned somewhere, also because it is not obvious (perhaps even counter-intuitive) from the "read" terminology.

(I know that a practical solution is to just `deepcopy` whatever I read from an open .jld file or just to avoid holding the .jld file open all the time (but this is impractical if one needs to read frequently from the same .jld file; the time taken to open/close then exceeds the time to read substantially))

**Comment by thchr** [comment]
Another point is that if I have a very large .jld file, consisting of very many variables and I were to read each of these variables sequentially at different points in time - each going in and out of scope, so that I only ever would deal with a small part of the .jld file's aggregate content - then this behavior effectively guarantees that all the accessed data stays in memory.

If the file is very large, it seems this could be quite undesirable.

**Comment by JonasIsensee** [comment]
Hi @thchr ,

this is a good point. This should definitely be mentioned in the documentation.
I don't think we'll be able to remove this and still keep JLD2 efficient - see below.

> Another point is that if I have a very large .jld file, consisting of very many variables and I were to read each of these variables sequentially at different points in time - each going in and out of scope, so that I only ever would deal with a small part of the .jld file's aggregate content - then this behavior effectively guarantees that all the accessed data stays in memory.

That is actually not a problem. JLD2 doesn't actually hold on to the memory but keeps a list of `WeakRef`s.
In that way, JLD2 will not keep the garbage collector from freeing the memory, but IF it is still there, it can be accessed.


Now, about why this is implemented in the first place:
JLD2 files are rather complex and they, for example, document the full datatype for each stored object. (Type signature + field names + field types) 
In order to still be fast, we don't want to decode the type for each object of the same type.
Another example is this:
```
julia> using JLD2
[ Info: Precompiling JLD2 [033835bb-8acc-5ee8-8aae-3f567f8a3819]

julia> x = rand(5)
5-element Array{Float64,1}:
 0.33329211572380313
 0.26626085758694984
 0.3589551627122194
 0.7030860957576452
 0.9332391003010014

julia> @save "test.jld2" a=(x,x)

julia> using FileIO

julia> a = load("test.jld2", "a")
([0.33329211572380313, 0.26626085758694984, 0.3589551627122194, 0.7030860957576452, 0.9332391003010014], [0.33329211572380313, 0.26626085758694984, 0.3589551627122194, 0.7030860957576452, 0.9332391003010014])

julia> a[1] === a[2]
true

julia> a[1][1] = 0.0
0.0

julia> a
([0.0, 0.26626085758694984, 0.3589551627122194, 0.7030860957576452, 0.9332391003010014], [0.0, 0.26626085758694984, 0.3589551627122194, 0.7030860957576452, 0.9332391003010014])
```

So, thanks to the caching procedure, JLD2 was able to correctly recreate my tuple that contained a single array twice.

If you'd like, I'll happily accept a PR to the docs :)
