### ISSUE TITLE
CodecZlib dependency 

### ISSUE THREAD

**Issue by srikumarks** [JuliaIO/JLD2.jl#321]
If the JLD2 library is used to save with compression turned on, then it seems to have a dependency with CodecZlib which then needs to be installed separately. Might be better to include it as a dependency of JLD2?

**Comment by JonasIsensee** [comment]
Hi @srikumarks ,

in previous versions, `CodecZlib` was listed as a dependency of `JLD2`.
I removed that at some point, because
 1) `JLD2` can be used without it
 2) I added compatibility to additional compression libraries, so no reason to favor one over the other

See https://juliaio.github.io/JLD2.jl/dev/compression/
