### ISSUE TITLE
delete or overwrite dataset or group?

### ISSUE THREAD

**Issue by sglyon** [JuliaIO/JLD2.jl#38]
Is is possible to delete or overwrite an dataset or a group with JLD2?

**Comment by simonster** [comment]
No. I didn't implement this because it's a lot of work to do properly. You need to be able to:

- Unlink datasets/groups from groups
- Keep track of holes in the file where datasets used to be, and put new data there
- When deleting an object with references to other objects, remove referenced objects that are not referenced by any other object (JLD actually doesn't do this, so deleting datasets will never free their references)
- Compact the file if there are large holes in it

**Comment by sglyon** [comment]
Sounds like a big job -- makes sense why it was left out. Thanks for explaining

**Comment by jw3126** [comment]
Would it be hard to be able to delete groups, without filling holes and without automatic compactification? However, a manual slow way to clean up a file would be needed. Like a `save` after a `load` should write a compact representation that does not contain unreferenced objects.

**Comment by JonasIsensee** [comment]
Hi @jw3126 !

yes, that should definitely be possible.
I'm not the original author of this library and don't fully understand the hdf5 format yet, but AFAICT at the end of each file we essentially write a table of contents with references to the data. To delete data, it should in principle be enough to open a file in `rw` mode, (that loads the toc as a dict internally), then delete entries from the toc and ensure that the toc is wrritten to file again.

For a more compact representation I would agree you need to move large amounts of data anyway so there is probably not much to gain from anything more advanced than just doing
```julia
data = load(filename)
save(filename, data)
```
(as you suggested)
```

**Comment by JonasIsensee** [comment]
Object deletion is now possible on master.
The dataset is not actually deleted but the entry in the parent group is removed.
