### ISSUE TITLE
UndefVarError: #68#new_logstate not defined

### ISSUE THREAD

**Issue by michaelschwob** [JuliaIO/JLD2.jl#471]
I just started receiving the following error when running `@save "save.jld2"`
```
ERROR: UndefVarError: #68#new_logstate not defined
Stacktrace:
 [1] top-level scope
   @ ~/.julia/packages/JLD2/ryhNR/src/loadsave.jl:86
```

I have no idea how to resolve this error, and it seems to have come about out of nowhere. This code was just working before. I didn't update any packages or remove the JLD2 package. I'm a bit confused on where this error is coming from.

**Comment by JonasIsensee** [comment]
Hi @michaelschwob,

I recommend that you avoid using `@save "file.jld2"` - in particular without supplying the variable names.
I understand that it is convenient, however from the library side it's not possible to do this right.
The macro has to somehow search through all names in Main and decide which to store and which to ignore.
`@save` has been made undocumented years ago.

What you are seeing is that julia or some library exported the name `#68#new_logstate` into `Main`.
I don't know what it is but it seems JLD2 can't deal with it properly but since it's a gensymed object it probably also shouldn't need to.

**Comment by michaelschwob** [comment]
I finally found the problem. The Suppressor package used in conjunction with JLD2 was giving this issue!

**Comment by michaelschwob** [comment]
> 

Thank you for your response and help!
