### ISSUE TITLE
Optional plain HDF5 data mapping without reconstruction of data source type

### ISSUE THREAD

**Issue by koehlerson** [JuliaIO/JLD2.jl#505]
As discussed in https://github.com/Ferrite-FEM/Ferrite.jl/issues/678 it would be nice to "dump" data sometimes, especially for the beginning of a computational project where structs change. The custom serialization interface offers a way to bijectively map from `A->Aserialized` (**and vice verca**). This, however, is sometimes not needed, instead, sometimes only certain fields need to be stored that can be expressed as Julia primitives/isbitstypes or arrays thereof. 

 As an example: Let's say I have a simulation with some struct that holds a state of a material that I'm simulating. This struct is not needed to reproduce the simulation but serves more as "intermediate" results that maybe relevant for postprocessing purposes. So, there is not really the need to store the full type or a custom serialization of it. Instead, I just want to store a single scalar of this type. See https://ferrite-fem.github.io/Ferrite.jl/stable/examples/plasticity/ especially the `MaterialState`. You only need the fields (all are `isbitstype` or primitives).
 
 What I envision is some function, let's call it for the sake of this issue `stuff_to_store` which is by default dispatched on `::Type{Any}` and is in this case the identity mapping. However, a user can now overload this function for their own struct and specify a `NamedTuple` of things to save. What should be expected from the user is that all fields of the `NamedTuple` are directly supported by HDF5 due to primitives,isbitstypes or arrays of these things. The tricky bit is now to call this for whatever should be stored and check if `stuff_to_save` is dispatched for the current object. If so, the `NamedTuple` is saved. In the case it isn't dispatched, the usual JLD2 machinery should kick in with all the nice features that are already implemented (including custom serialization).
 
 By this, one could achieve an optional "plain HDF5" storage behavior in JLD2. I'm not quite sure where to start to tackle this problem, but as @JonasIsensee pointed out a seperate package on top of JLD2 would be a good start. In order to be helpful I'd need some guidance where we could sneak in such dispatches. The aforementioned things are already packed with implementation detail even tho it isn't meant to be. More or less everything should be understood as an example how to get to an optional "plain HDF5" storage scheme within JLD2.

**Comment by koehlerson** [comment]
Along that lines, I do think that the same people who would be interested in something like this, would be interested in syntactic sugar for  https://github.com/JuliaIO/JLD2.jl/issues/504, i.e. something like `file["field"][]` returns the `NamedTuple` representation or any other barebone representation

**Comment by JonasIsensee** [comment]
> Along that lines, I do think that the same people who would be interested in something like this, would be interested in syntactic sugar for #504, i.e. something like `file["field"][]` returns the `NamedTuple` representation or any other barebone representation

That sounds nice. This syntax `file["field"][]` sadly can't work, since `file["field"]` already tries to load the regular struct before the second `getindex` is called. Something like `file["field", :plain]` could work. `HDF5.jl` works with that kind of syntax.

**Comment by koehlerson** [comment]
that sounds nice!

**Comment by JonasIsensee** [comment]
I like this idea of an optional `bijection`.

The place to start, I'd say, is to define the expected behaviour and desired API style.
E.g.
- Do you want to implement a conversion function? Or give a list of fields to keep?
- How should it compose: 
   - only convert at toplevel (no nesting)
   - Partial nesting: Require that the result named tuple only contains basic types and other (same) converted structures. Do not mix with regular structs.
   - full nesting: recursively convert all instances
   Potential problem: the conversion is not a bijection. Loading of (normal) structs with converted fields will not work.

**Comment by JonasIsensee** [comment]
@koehlerson you probably didn't get notifications after I first commented with an incomplete message.
What are your thoughts?

To start playing around with ideas, one doesn't really need to work with JLD2 at all.
I think it would be sufficient to use something like
```
struct MockFile
    d::Dict{String,Any}
end
```

and build an interface that does the desired things.
This could then be tested against.

**Comment by JonasIsensee** [comment]
> Why I'm unsure if I can follow is the following

>>    Loading of (normal) structs with converted fields will not work.

Here's an example of a fundamental problem.
This already errors and would also error when you don't try to reconstruct types.
The only way to change this, I guess, would be to disallow non-concrete element types (except Any).
Here, the parent "structure" was just an array, but the same issue would appear for abstract type-restricted struct fields.

```
julia> struct N <: Real; x::Int; end

julia> arr = Real[1, 2, N(3)]
3-element Vector{Real}:
    1
    2
 N(3)

julia> jldsave("test.jld2"; arr)

## new session 
julia> load("test.jld2")
┌ Warning: type Main.N does not exist in workspace; reconstructing
└ @ JLD2 ~/.julia/dev/JLD2.jl/src/data/reconstructing_datatypes.jl:605
Error encountered while load FileIO.File{FileIO.DataFormat{:JLD2}, String}("test.jld2").

Fatal error:
ERROR: MethodError: Cannot `convert` an object of type JLD2.ReconstructedStatic{:N, (:x,), Tuple{Int64}} to an object of type Real
```

**Comment by JonasIsensee** [comment]
I'm sorry, this is a complex topic and so my answers will be a bit disorganized.
In my view, there are few problems that could be addressed here.

1) Some objects have type signatures that JLD2 cannot store. `CustomSerialization` can not help here, because converts the data but still it tries to encode the originial type signature for loading.
2) Some objects are (heavily nested) and immutable. JLD2 tries to inline immutable fields which yieds a struct that is too large for the HDF5 standard. (64kb is max for type description. This is what happens in #487.
Both (1) and (2) need different encoding in the file and if reconstruction is desired, some new way to encode the type signature.

3) Some very basic julia objects such as `Vector{Real}` can be almost impossible to reconstruct in JLD2 currently. Anyone can define new subtypes that may be missing on load. It is not possible to detect this on the type-level and namedtuples won't fit be `<: Real`. One could possibly try to reconstruct all abstract types e.g. `Real` as `Any`  but someone would have to try. [ Quick background info: When loading, JLD2 retrieves all the type infos and generates fairly efficient and type-stable code that then loads the data from top to bottom. This is necessary to make things fast but inevitable fails when unexpected types pop up somewhere in between ]

**Comment by JonasIsensee** [comment]
Please test out #522.

I can't say it's elegant but it worked for my test cases.
