### ISSUE TITLE
What is suggested way to store a JLD2 file, Julia struct or Dict?

### ISSUE THREAD

**Issue by hz-xiaxz** [JuliaIO/JLD2.jl#585]
Hello, I'm new to JLD2 and have a problem in efficiently dumping JLD2 type.

Suppose I have got a dataset like 
```julia
struct data
A::Vector{Float64}
B::Vector{Float64}
C::Vector{Float64}
```

where `A,B,C` are literally same length vectors (for some reason I didn't use `SVector`s, but if using that will improve performance, I think I'll try)

The data will be stored in each iteration, so I dumped a `Dict` data type into the JLD2 file, like `Dict{String, data}`. where the dictionary key labels the `iteration time` 

Note that I could also create a `group` in the JLD2 file, name the group as the `iteration time`, and store a `Dict{String, AbstractVector}` under the group.

I wonder if there is performance difference between the stored Julia `struct` and `Dict`? Or is there a suggested way? 

The struct construction might be mandatory because I perform function dispatch with that `data` struct in source.

Thanks much for your help!

**Comment by JonasIsensee** [comment]
Your structure looks simple enough so that you can generate it with random data.
Maybe you can try and compare different options?

I do not think you will find significant performance penalties for any of the methods.
However, it's not necessary to wrap your data into dicts.

My gut feeling tells me, explicitly creating a group and then doing 

`group[dataname] = data`

would be fastest, but could test.
