### ISSUE TITLE
Incompatibility with Julia 1.12 due to missing `Base.module_keys`

### ISSUE THREAD

**Issue by kbarros** [JuliaIO/JLD2.jl#614]
There are a couple places where JLD2 currently depends on `Base.module_keys`:
https://github.com/search?q=repo%3AJuliaIO%2FJLD2.jl%20module_keys&type=code

This function is no longer available on nightly (1.12) versions of Julia, which makes JLD2 incompatible.

**Comment by giordano** [comment]
This was changed in https://github.com/JuliaLang/julia/pull/56329, my understanding is that `Base.module_keys` was replaced by `Base.loaded_modules_order` (but with a different type, and apparently also a different list of modules)

**Comment by kbarros** [comment]
Another option to consider is `values(Base.loaded_modules)`. I'm not sure how that's distinct from `Base.loaded_modules_order`. Either way, these functions seem available across Julia versions (I looked at 1.10, 1.11, 1.12-dev).

Here are some links to show how `Base.loaded_modules_order` gets filled in different versions:
https://github.com/JuliaLang/julia/blob/release-1.10/base/loading.jl#L1859-L1861
https://github.com/JuliaLang/julia/blob/master/base/loading.jl#L2530-L2531

Of course, all of this functions seems to be private. Ideally one could find an alternative that's in the public API?

**Comment by JonasIsensee** [comment]
Since I haven't needed to drop support for julia 1.6, yet, I went with `values(Base.loaded_modules)` which has been around forever. (`Base.loaded_modules_order` was added in julia v1.9)

I'd love an alternative using public API only, but that's no reason to leave it broken until then.

A new release with fix should hopefully be out later today.
