### ISSUE TITLE
can't reconstruct Date in v0.7

### ISSUE THREAD

**Issue by tpapp** [JuliaIO/JLD2.jl#82]
MWE:
```julia
using Dates: Date
import JLD2
using FileIO: load, save

t = (1, Date(1,2,3))
save("/tmp/f.jld2", "t", t)
t2 = load("/tmp/f.jld2")["t"]
t == t2                         # false
```

```julia
julia> t2
(1, getfield(JLD2.ReconstructedTypes, Symbol("##Date#378"))(getfield(JLD2.ReconstructedTypes, Symbol("##UTInstant{getfield(JLD2.ReconstructedTypes, Symbol("##Day#376"))}#377"))(getfield(JLD2.ReconstructedTypes, Symbol("##Day#376"))(34))))

julia> VERSION
v"0.7.0-beta2.1"
```

**Comment by alandion** [comment]
[https://github.com/simonster/JLD2.jl/blob/e84b06eb72b850048453df13fdd7f685ce213225/src/data.jl#L851](url)
This issue seems to come down to to `parentmodule(Dates)` return `Dates` .  This problem can be worked around in JLD2 by adding and extra `push!(tn, nameof(m))` after the while loop linked above, but perhaps the behavior of parentmodule is a bug in Base?

**Comment by tpapp** [comment]
@alandion: thanks for the help, I made a PR for it.

**Comment by JonasIsensee** [comment]
This seems to no longer be a problem.
